Repository pagopa/selfcare-infra, pull requests merged in 2023-07, with the labels that each got.

#375 [SELC - 2548] change App IO and IO premium content
  src/core/contracts_template/io-premium/1.0.0/io-premium-accordo_di_adesione-v.1.0.0.html
  src/core/contracts_template/io/2.4.2/io-accordo_di_adesione-v.2.4.2.html
  src/domains/pnpg-app/10_selc_configmaps.tf
  src/domains/pnpg-app/README.md
Labels: status: applied, DEV, UAT

#378 Removed required fields from API response resources and added AOO/UO …
  src/core/api/ms_external_api/v2/open-api.yml.tpl
Labels: status: applied, DEV

#382 [SELC - 2615] Add new pn contract version
  src/core/contracts_template/pn/2.0.0/pn-accordo_di_adesione-v.2.0.0.html
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/domains/pnpg-common/02_mongodb.tf
  src/domains/pnpg-common/README.md
Labels: status: applied, DEV, UAT, PROD

#384 Remove ms-core from app gateway
  src/core/04_appgateway.tf
Labels: status: applied, DEV, UAT, PROD

#391 feat: Updated devops agent, separated between infra and app
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines.yml
  .devops/pnpg-code-review-pipelines.yml
  src/core/99_variables.tf
  src/core/README.md
  src/core/azure_devops_agent.tf
  src/core/tflist
  src/packer/.terraform.lock.hcl
  src/packer/01_azure_devops_agent.tf
  src/packer/99_main.tf
  src/packer/99_main.tf.ci
  src/packer/99_variables.tf
  src/packer/README.md
  src/packer/env/dev/backend.ini
  src/packer/env/dev/backend.tfvars
  src/packer/env/dev/terraform.tfvars
  src/packer/env/prod/backend.ini
  src/packer/env/prod/backend.tfvars
  src/packer/env/prod/terraform.tfvars
  src/packer/env/uat/backend.ini
  src/packer/env/uat/backend.tfvars
  src/packer/env/uat/terraform.tfvars
  src/packer/terraform.sh
Labels: status: applied

#385 docs: add new interop contract version -> 2.1.0
  src/core/contracts_template/interop/2.1.0/interop-accordo_di_adesione-v.2.1.0.html
Labels: status: applied, DEV, UAT

#395 added configurations to external-ionterceptor event secrets
  src/k8s/selc_secrets.tf
Labels: status: applied, DEV, UAT

#397 [SELC - 2724] - update mail template for io massive import
  src/core/contracts_template/mail/import-massivo-io/1.0.0.json
Labels: status: applied, DEV, UAT

#400 [SELC - 2700 ] added api to retrieve delegations
  src/core/.terraform.lock.hcl
  src/core/api/ms_external_api/v2/getDelegationsUsingGET_op_policy.xml.tpl
  src/core/api/ms_external_api/v2/open-api.yml.tpl
  src/core/apim.tf
Labels: status: applied, DEV, UAT

#396 Acknowledgment api for external interceptor
  src/core/README.md
  src/core/api/ms_external_api/v2/messageAcknowledgment_op_policy.xml.tpl
  src/core/api/ms_external_api/v2/open-api.yml.tpl
  src/core/apim.tf
  src/domains/pnpg-app/80_tls_checker.tf
  src/domains/pnpg-app/README.md
  src/k8s/06_tls_cert_check.tf
  src/k8s/README.md
Labels: status: applied, DEV

#403 feat: added STORAGE_TEMPLATE_URL
  src/domains/pnpg-app/.terraform.lock.hcl
  src/domains/pnpg-app/10_selc_secrets.tf
  src/k8s/.terraform.lock.hcl
  src/k8s/selc_secrets.tf
Labels: status: applied, DEV, UAT

#404 fix: Add new tls checker params
  src/domains/pnpg-app/80_tls_checker.tf
  src/domains/pnpg-app/README.md
  src/domains/pnpg-app/env/dev/terraform.tfvars
  src/domains/pnpg-app/env/prod/terraform.tfvars
  src/domains/pnpg-app/env/uat/terraform.tfvars
Labels: status: applied, DEV, UAT, PROD
