Repository pagopa/selfcare-infra, pull requests merged in 2023-06, with the labels that each got.

#351 added mail import massivo io
  src/core/README.md
  src/core/contracts_template/mail/import-massivo-io/1.0.0.json
  src/domains/pnpg-app/10_selc_configmaps.tf
  src/k8s/selc_configmaps.tf
Labels: status: applied, DEV, UAT, PROD

#355 fix : modified mail content for io
  src/core/contracts_template/mail/import-massivo-io/1.0.0.json
Labels: status: applied, DEV, UAT, PROD

#358 fix: Update url mapping for party migration
  src/k8s/selc_configmaps.tf
Labels: status: applied, PROD

#356 fix: Modified support mail
  src/core/contracts_template/mail/import-massivo-io/1.0.0.json
  src/domains/pnpg-app/01_secrets.tf
  src/domains/pnpg-common/03_cdn.tf
Labels: status: applied, DEV, UAT, PROD

#347 fix: Update endpoint for party migration to core micro service
  src/core/apim.tf
Labels: status: applied, DEV, UAT

#363 fix: PN eventhub prod
  src/core/env/prod/terraform.tfvars
Labels: status: applied, PROD

#365 fix: Apim internal removing party-process
  src/core/api/ms_internal_api/v1/getInstitution_op_policy.xml.tpl
  src/core/apim.tf
  src/core/env/prod/terraform.tfvars
Labels: status: applied, PROD

#361 [SELC - 2460] - modified support mail for contract template
  src/core/README.md
  src/core/apim.tf
  src/core/contracts_template/mail/1.0.0.json
  src/core/contracts_template/mail/onboarding-complete/1.0.0.json
  src/core/contracts_template/mail/onboarding-notification/1.0.0.json
  src/core/contracts_template/mail/onboarding-refused/1.0.0.json
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/k8s/README.md
  src/k8s/selc_secrets.tf
Labels: status: applied, DEV, UAT

#366 [SELC - 2354] - modified support email for user mail template
  src/core/.terraform.lock.hcl
  src/core/resources/templates/email/user_activated.ftlh
  src/core/resources/templates/email/user_added_multi_role.ftlh
  src/core/resources/templates/email/user_added_single_role.ftlh
  src/core/resources/templates/email/user_complete_single_role.ftlh
  src/core/resources/templates/email/user_deleted.ftlh
  src/core/resources/templates/email/user_suspended.ftlh
Labels: status: applied, UAT

#374 [SELC - 2513] - change CEO in PSP pagopa contract
  src/core/contracts_template/pagopa/1.0.0/pagopa-accordo_di_adesione_psp-v.1.0.0.html
Labels: status: applied, DEV, UAT, PROD
