Repository pagopa/selfcare-infra, pull requests merged in 2023-11, with the labels that each got.

#507 Update metadata AGID SPID with new certificate
  src/core/env/prod/spid/metadata.xml
Labels: status: applied, PROD

#499 [SELC-3290] feat: Add api for AutoApprovalOnboardingFromPDA in internal-api
  src/core/api/ms_external_api/v2/open-api.yml.tpl
  src/core/api/ms_internal_api/v1/core_op_policy.xml.tpl
  src/core/api/ms_internal_api/v1/internal_jwt_base_policy.xml.tpl
  src/core/api/ms_internal_api/v1/open-api.yml.tpl
  src/core/apim.tf
  src/k8s/.terraform.lock.hcl
  src/k8s/99_variables.tf
  src/k8s/selc_configmaps.tf
  src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
  src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
  src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
Labels: status: applied, DEV

#509 Adding new ingress path due to new hub-spid-login ms
  src/core/04_appgateway.tf
Labels: status: applied, DEV, PROD

#510 [SELC - 3330] feat: added city, country, county params in InstitutionResource, Inst…
  src/core/api/ms_external_api/v2/open-api.yml.tpl
Labels: status: applied, DEV, UAT

#518 Add new institutions to ANAC data.csv
  src/core/resources/anac/data.csv
Labels: status: applied, PROD

#524 Add pub-op-full to metadata
  src/core/README.md
  src/core/env/prod/spid/metadata.xml
Labels: status: applied, PROD

#526 Adding product-io-premium and remove prod-test-io*
  src/core/api_product/io-premium/policy.xml
  src/core/apim.tf
Labels: status: applied, UAT, PROD

#542 feat: added new interop and io-sign contract version
  src/core/contracts_template/interop/2.3.1/interop-accordo_di_adesione-v.2.3.1.html
  src/core/contracts_template/io-sign/1.0.1/io_sign-accordo_di_adesione-v.1.0.1.html
Labels: status: applied, DEV, UAT

#543 [SELC - 3443] feat: added new and updated anac-data.csv file
  src/core/resources/anac/data.csv
Labels: status: applied, DEV, UAT

#553 Add new ANAC file 2023-11-27
  src/core/resources/anac/data.csv
Labels: status: applied, PROD

#554 [SELC - 3483]feat: updated body for io massive import
  src/core/README.md
  src/core/contracts_template/mail/import-massivo-io/1.0.0.json
  src/core/monitor.tf
Labels: status: applied, DEV, UAT, PROD

#557 fix: Token exchange url
  src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
  src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
  src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
Labels: status: applied, PROD
