Repository pagopa/selfcare-infra, pull requests merged in 2023-01, with the labels that each got.

#236 Feature/selc 1823
  src/core/contracts_template/io-premium/1.0.0/io-premium-accordo_di_adesione-v.1.0.0.html
  src/core/contracts_template/io/2.3.3/io-accordo_di_adesione-v.2.3.3.html
  src/core/contracts_template/io/2.4.0/io-accordo_di_adesione-v.2.4.0.html
Labels: status: applied, DEV, UAT, PROD

#243 Feature/selc 1901
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
Labels: status: applied, UAT

#246 addition of a first version of the new "pn" contract
  src/core/contracts_template/pn/1.0.0/pn-accordo_di_adesione-v.1.0.0.html
Labels: DEV
