Repository pagopa/selfcare-infra, pull requests merged in 2023-08, with the labels that each got.

#402 Added secret key for zendesk integration
  src/k8s/00_secrets.tf
  src/k8s/README.md
  src/k8s/selc_secrets.tf
Labels: status: applied, DEV, UAT

#392 Feature/selc 2604
  src/core/api/ms_external_api/v2/getInstitutionsByTaxCodeUsingGET_op_policy.xml.tpl
  src/core/api/ms_external_api/v2/getOnboardingsInstitutionUsingGET_op_policy.xml.tpl
  src/core/api/ms_external_api/v2/jwt_auth_op_policy_v2.xml.tpl
  src/core/api/ms_external_api/v2/open-api.yml.tpl
  src/core/apim.tf
Labels: status: applied, DEV, UAT

#406 [SELC - 2781]fix: updated open-api
  src/core/api/ms_external_api/v2/open-api.yml.tpl
Labels: status: applied, DEV, UAT

#408 add secret to external-interceptor
  src/k8s/selc_secrets.tf
Labels: status: applied, DEV

#410 [SFEQS-1920] Add dns_ns_record for firmaconio_selfcare
  src/core/02_dns_public.tf
  src/core/README.md
  src/core/env/uat/terraform.tfvars
Labels: status: applied, PROD

#414 add interop consumer to eventhub sc-contracts
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
Labels: status: applied, DEV, UAT, PROD

#411 [SELC - 2805] updated interop contract text
  src/core/contracts_template/interop/2.1.0/interop-accordo_di_adesione-v.2.1.0.html
Labels: status: applied, DEV, UAT

#415 Fix parameter for auto approval onboarding into open-api
  src/core/api/ms_internal_api/v1/open-api.yml.tpl
Labels: status: applied, DEV, UAT

#420 add secrets for calling registry proxy using k8s token for external i…
  src/k8s/00_secrets.tf
  src/k8s/selc_secrets.tf
Labels: status: applied, DEV

#423 Add new APIM product for pnpg
  src/core/api/ms_external_api/v2/getInstitution_op_policy.xml.tpl
  src/domains/pnpg-app/06_selc_apim_pnpg.tf
  src/domains/pnpg-app/README.md
  src/domains/pnpg-app/api_product/pnpg_hotfix/policy.xml
Labels: status: applied, DEV

#427 Deleted root parent node construction from response
  src/core/api/ms_external_api/v2/getInstitution_op_policy.xml.tpl
Labels: status: applied, DEV

#429 [SELC - 2857] updated pagopa manager name
  src/core/contracts_template/io-sign/1.0.0/io_sign-accordo_di_adesione-v.1.0.0.html
Labels: status: applied, DEV, UAT
