Repository pagopa/selfcare-infra, pull requests merged in 2023-10, with the labels that each got.

#466 Modified contract's template for interop 2.3
  src/core/contracts_template/interop/2.3.0/interop-accordo_di_adesione-v.2.3.0.html
Labels: status: applied, DEV, UAT

#467 [SELC - 3112] added PT registration mail and variable to configmaps
  src/core/contracts_template/mail/registration-notification-admin/1.0.0.json
  src/core/contracts_template/mail/registration-request-pt/1.0.0.json
  src/k8s/selc_configmaps.tf
Labels: status: applied, DEV

#471 Added reference to email for partner registration completed
  src/core/contracts_template/mail/registration-complete-pt/1.0.0.json
  src/k8s/selc_configmaps.tf
Labels: status: applied, DEV, UAT

#479 [SELC-3220] feat: added AS institution type in open api
  src/core/api/ms_external_api/v2/open-api.yml.tpl
  src/core/api/selfcare_support_service/v1/getContract_op_policy.xml.tpl
  src/core/api/selfcare_support_service/v1/open-api.yml.tpl
Labels: status: applied, DEV, UAT

#481 Adding new IP mask for eventhub firewall on product FD
  src/core/env/prod/terraform.tfvars
Labels: status: ready to apply, PROD

#482 [SELC-3149] fix: add Api on Apim for migration Tool
  src/core/api/ms_external_api/v2/core_op_policy.xml.tpl
  src/core/api/ms_external_api/v2/open-api.yml.tpl
  src/core/api/party_registry_proxy/v1/open-api.yml.tpl
  src/core/apim.tf
  src/k8s/selc_configmaps.tf
Labels: status: applied, DEV, UAT

#484 Adding alert message json file
  src/core/README.md
  src/core/assets.tf
  src/core/env/dev/assets/login-alert-message.json
  src/core/env/prod/assets/login-alert-message.json
  src/core/env/uat/assets/login-alert-message.json
  src/domains/pnpg-app/05_assets.tf
  src/domains/pnpg-app/README.md
  src/domains/pnpg-app/env/dev/assets/login-alert-message.json
  src/domains/pnpg-app/env/prod/assets/login-alert-message.json
  src/domains/pnpg-app/env/uat/assets/login-alert-message.json
Labels: status: applied, DEV, UAT, PROD

#487 Remove enable field for pnpg
  src/domains/pnpg-app/env/prod/assets/login-alert-message.json
Labels: status: applied, PROD

#486 fiat: Update alert data
  src/aks-platform/00_monitor.tf
  src/aks-platform/99_variables.tf
  src/aks-platform/README.md
  src/core/04_appgateway.tf
  src/core/README.md
  src/core/aks.tf
  src/core/events.tf
  src/core/monitor.tf
  src/core/postgres.tf
  src/domains/pnpg-app/00_monitor.tf
  src/domains/pnpg-app/99_variables.tf
  src/domains/pnpg-app/README.md
  src/k8s/locals.tf
Labels: status: applied, DEV, UAT, PROD

#475 adding new hub spid login
  src/core/01_key_vault_operations.tf
  src/core/README.md
  src/core/env/dev/spid/metadata.xml
  src/core/env/dev/spid_testenv_conf/config.yaml
  src/core/env/prod/spid/metadata.xml
  src/core/env/uat/spid/metadata.xml
  src/core/env/uat/spid_testenv_conf/config.yaml
  src/core/resources.tf
  src/core/spid-testenv.tf
  src/core/utils/sh/renew-jwt.sh
  src/k8s/.terraform.lock.hcl
  src/k8s/00_secrets.tf
  src/k8s/README.md
  src/k8s/selc_configmaps.tf
  src/k8s/selc_ingress.tf
  src/k8s/selc_secrets.tf
Labels: status: applied, DEV, UAT, PROD

#490 increment min and max capacity
  src/core/env/prod/terraform.tfvars
Labels: status: applied, PROD

#493 [SELC-3225] feat: added resource for ivass data file
  src/core/README.md
  src/core/resources.tf
  src/core/resources/ivass/data.csv
Labels: status: applied, DEV, UAT

#494 add new entry to procurement data source
  src/core/resources/anac/data.csv
Labels: status: applied, PROD

#497 fix: Update open api for support service api
  src/core/api/selfcare_support_service/v1/open-api.yml.tpl
Labels: status: applied, DEV, UAT

#498 Add new entry to procurement data source
  src/core/resources/anac/data.csv
Labels: status: applied, PROD

#500 Add Logo to external-api.v2 to Institution resurce
  src/core/api/ms_external_api/v2/open-api.yml.tpl
  src/core/apim.tf
Labels: status: applied, DEV, UAT

#504 Update alert message on prod
  src/core/env/prod/assets/login-alert-message.json
Labels: status: applied, PROD

#505 Removing web hoot opsgenie from alerts
  src/core/monitor.tf
Labels: status: applied, PROD
