Repository pagopa/selfcare-infra, pull requests merged in 2024-02, with the labels that each got.

#621 [SELC-3995] feat: update api-doc for API zendesk
  src/core/api/ms_external_api/v2/open-api.yml.tpl
Labels: status: applied, DEV, UAT

#623 modified rewrite rule in appgateway
  src/core/04_appgateway.tf
Labels: status: applied, DEV, UAT, PROD

#629 feat: Add Notification Event to APIM
  src/core/README.md
  src/core/api/notification_event_api/v1/internal_jwt_base_policy.xml.tpl
  src/core/apim.tf
Labels: status: applied, PROD

#630 fix: Remove userIdForAuth from getInstitutionProductUsersUsingGET
  src/core/api/ms_external_api/v2/getInstitutionProductUsersUsingGET_op_policy.xml.tpl
  src/core/api/ms_external_api/v2/open-api.yml.tpl
Labels: status: applied, DEV, UAT, PROD
