Repository pagopa/selfcare-infra, pull requests merged in 2024-01, with the labels that each got.

#590 [SELC - 3687] feat: added complete onboarding without signature verification API to…
  src/core/api/ms_internal_api/v1/open-api.yml.tpl
  src/core/apim.tf
Labels: status: applied, DEV, UAT

#591 feature/SELC-3720
  src/core/contracts_template/mail/delegation-notification/user-1.0.0.json
  src/k8s/selc_configmaps.tf
Labels: status: applied, DEV, UAT

#595 add selfcare aws ses
  src/k8s/.terraform.lock.hcl
  src/k8s/selc_secrets.tf
Labels: status: applied, DEV, UAT, PROD

#594 [SELC-3692] feat: added API getAllTokens and getAllUsers
  src/core/api/selfcare_support_service/v1/getAllTokensUsingGET_op_policy.xml.tpl
  src/core/api/selfcare_support_service/v1/getUsersUsingGET_op_policy.xml.tpl
  src/core/api/selfcare_support_service/v1/open-api.yml.tpl
  src/core/apim.tf
Labels: status: applied, DEV, UAT

#592 Adding new azurerm_dns_zone for areariservata.pagopa.it
  src/core/02_dns_public_areariservata.tf
  src/core/99_variables.tf
  src/core/README.md
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/domains/pnpg-app/00_network.tf
  src/domains/pnpg-app/99_variables.tf
  src/domains/pnpg-common/00_dns_public.tf
Labels: status: applied, DEV, UAT, PROD

#598 [SELC-3307] feat: modify url key in API External v2
  src/core/api/ms_external_api/v2/getInstitution_op_policy.xml.tpl
  src/core/api/ms_external_api/v2/getInstitutions_op_policy.xml.tpl
  src/core/apim.tf
Labels: status: applied, DEV, UAT

#602 Fix: Test url maps adding configuration for notifcation to opsgenie
  src/core/monitor.tf
Labels: status: applied, PROD

#605 IVASS file 2023-01-23
  src/core/resources/ivass/data.csv
Labels: status: applied, PROD

#608 adding productId to getAllToken
  src/core/api/selfcare_support_service/v1/core_op_policy.xml.tpl
  src/core/api/selfcare_support_service/v1/getDelegationsUsingGET_op_policy.xml.tpl
  src/core/api/selfcare_support_service/v1/getInstitutionsByTaxCodeUsingGET_op_policy.xml.tpl
  src/core/api/selfcare_support_service/v1/jwt_auth_op_policy.xml.tpl
  src/core/api/selfcare_support_service/v1/open-api.yml.tpl
  src/core/api/selfcare_support_service/v1/postOnboardingInstitutionUsers_op_policy.xml.tpl
  src/core/api/selfcare_support_service/v1/support_op_policy.xml.tpl
  src/core/apim.tf
Labels: status: applied, PROD

#615 [SELC-4015] feat: remove autoApprovalOnboarding api from internal apim
  src/core/api/ms_internal_api/v1/open-api.yml.tpl
  src/core/apim.tf
Labels: status: applied, DEV, UAT
