Repository pagopa/selfcare-infra, pull requests merged in 2024-05, with the labels that each got.

#680 Add apim internal resendContractsByInstitutionIdAndTokenIdUsingPUT
  src/core/api/ms_internal_api/v1/open-api.yml.tpl
  src/core/apim.tf
Labels: status: ready to apply, PROD

#689 [SELC-4795] feat: Updated contract for prod-pagopa and institutionType EC
  src/core/README.md
  src/core/contracts_template/pagopa/1.0.0/pagopa-accordo_di_adesione_ec-v.1.0.0.html
  src/core/env/dev/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/domains/pnpg-app/README.md
Labels: status: applied, DEV, UAT

#692 [SELC-4930] feat: add API getUserInstitutionUsingGET in external-v2
  src/core/api/ms_external_api/v2/getUserInstitutionUsingGet_op_policy.xml.tpl
  src/core/api/ms_external_api/v2/open-api.yml.tpl
  src/core/apim.tf
Labels: status: applied, DEV
