Repository pagopa/selfcare-infra, pull requests merged in 2024-06, with the labels that each got.

#698 [SELC - 5032] feat: added api to retrive institution onboardings to support module apim
  src/core/api/selfcare_support_service/v1/open-api.yml.tpl
  src/core/apim.tf
  src/core/mongodb.tf
  src/domains/pnpg-app/06_selc_apim_pnpg.tf
  src/domains/pnpg-app/README.md
Labels: status: applied, DEV, UAT, PROD

#700 [SELC-5053] feat: remove getUsersUsingGET and modify getTokens support API
  src/core/api/selfcare_support_service/v1/open-api.yml.tpl
  src/core/apim.tf
Labels: status: applied, DEV

#707 [SELC-5132] Update IVASS open data
  src/core/resources/ivass/data.csv
Labels: status: ready to apply, DEV, UAT, PROD

#713 feat: Added base64 complete user request
  src/core/contracts_template/mail/onboarding-complete-user/1.0.0.json
Labels: status: applied, DEV

#708 [SELC - 5069] feat: added new email template for aggregator
  src/core/contracts_template/mail/onboarding-request-aggregator/1.0.0.json
Labels: status: applied, DEV

#648 [SELC-4448] fix: Migration nat from onboarding function to globally
  src/core/.terraform.lock.hcl
  src/core/02_nat.tf
  src/core/99_main.tf
  src/core/99_variables.tf
  src/core/README.md
  src/core/aks.tf
  src/domains/pnpg-app/02_nat.tf
  src/domains/pnpg-app/99_variables.tf
  src/domains/pnpg-app/README.md
Labels: status: applied, DEV, UAT, PROD

#716 [SELC - 5069] feat: added new template mail for onboarding aggregator
  src/core/.terraform.lock.hcl
Labels: status: applied, DEV

#703 [SELC-5088] Add new update onboarding api to apim support
  src/core/api/selfcare_support_service/v1/open-api.yml.tpl
  src/core/apim.tf
Labels: status: applied, DEV, UAT, PROD
