Repository pagopa/selfcare-infra, pull requests merged in 2024-03, with the labels that each got.

#637 removing postgresdb
  src/core/99_variables.tf
  src/core/README.md
  src/core/env/dev/terraform.tfvars
  src/core/env/prod/terraform.tfvars
  src/core/env/uat/terraform.tfvars
  src/core/outputs.tf
  src/core/postgres.tf
  src/domains/pnpg-app/00_secrets.tf
  src/domains/pnpg-app/10_selc_secrets.tf
  src/domains/pnpg-app/99_variables.tf
  src/domains/pnpg-app/README.md
  src/domains/pnpg-app/env/dev/terraform.tfvars
  src/domains/pnpg-app/env/prod/terraform.tfvars
  src/domains/pnpg-app/env/uat/terraform.tfvars
  src/k8s/00_secrets.tf
  src/k8s/99_variables.tf
  src/k8s/README.md
  src/k8s/locals.tf
  src/k8s/selc_configmaps.tf
  src/k8s/selc_secrets.tf
  src/k8s/subscriptions/DEV-SelfCare/terraform.tfvars
  src/k8s/subscriptions/PROD-SelfCare/terraform.tfvars
  src/k8s/subscriptions/UAT-SelfCare/terraform.tfvars
  src/psql/flyway.sh
  src/psql/migrations/remove/U1__users.sql
  src/psql/migrations/remove/U2__party.sql
  src/psql/migrations/remove/U3__party_projection.sql
  src/psql/migrations/selc/V1__user.sql
  src/psql/migrations/selc/V2__party.sql
  src/psql/migrations/selc/V3__party_projection.sql
Labels: status: applied, DEV, UAT, PROD

#632 Upgrade mongo version to from 4.0 to 4.2
  src/core/mongodb.tf
Labels: status: applied, DEV, UAT, PROD

#633 [SELC-3924] fix: added resource to create secret for event hub sc-contracts
  src/core/README.md
  src/core/events.tf
  src/k8s/selc_secrets.tf
Labels: status: applied, DEV, UAT

#639 [SELC-4432] feat: Add new apim product for prod-interop-atst
  src/core/README.md
  src/core/api_product/interop-atst/policy.xml
  src/core/apim.tf
Labels: status: applied, DEV, UAT

#646 Add search param to getDelegationsUsingGET
  src/core/api/ms_external_api/v2/open-api.yml.tpl
  src/core/api/selfcare_support_service/v1/open-api.yml.tpl
Labels: status: applied, DEV, UAT, PROD

#647 [SELC - 4401] feat: updated onboarding refused mail template and updated MAIL_TEMP…
  src/core/contracts_template/mail/onboarding-refused/1.0.1.json
  src/k8s/selc_configmaps.tf
Labels: status: applied, DEV, UAT, PROD

#649 [SELC-4529] feat: added secret for event hub keys in lower case
  src/core/events.tf
Labels: status: applied, DEV, UAT

#650 feat: Adding new IP for prod-interop-atst
  src/core/env/prod/terraform.tfvars
Labels: status: applied, PROD

#652 feat: [SELC-4352] add new version of onboarding request mail template
  src/core/contracts_template/mail/onboarding-request/1.0.0.json
  src/core/contracts_template/mail/onboarding-request/1.0.1.json
  src/domains/pnpg-app/10_selc_configmaps.tf
  src/k8s/selc_configmaps.tf
Labels: status: applied, DEV, UAT
